# Generated by Django 3.2 on 2024-05-03 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('IpcTipoDivision', '0001_initial'),
        ('Ipc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpcDivision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_mensual', models.CharField(max_length=250)),
                ('valor_interanual', models.CharField(max_length=250)),
                ('ipc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ipc.ipc')),
                ('tipo_division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IpcTipoDivision.tipodivision')),
            ],
        ),
    ]
