# Generated by Django 3.2 on 2024-05-15 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Año', '0001_initial'),
        ('TipoValor', '0001_initial'),
        ('Mes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RamaActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rama', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='RemuneracionRama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registrado_con_estacionalidad', models.CharField(max_length=250)),
                ('año', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Año.año')),
                ('mes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mes.mes')),
                ('rama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sectorPrivado.ramaactividad')),
                ('tipo_valor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TipoValor.tipovalor')),
            ],
        ),
        migrations.CreateModel(
            name='Remuneracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promedio_estacionalidad', models.CharField(max_length=250)),
                ('var_intermensual', models.CharField(max_length=250)),
                ('var_interanual', models.CharField(max_length=250)),
                ('año', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Año.año')),
                ('mes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mes.mes')),
                ('tipo_valor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TipoValor.tipovalor')),
            ],
        ),
        migrations.CreateModel(
            name='AsalariadosRegistrados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_sin_estacionalidad', models.CharField(max_length=250)),
                ('dif_intermensual', models.CharField(max_length=250)),
                ('dif_interanual', models.CharField(max_length=250)),
                ('var_intermensual', models.CharField(max_length=250)),
                ('var_interanual', models.CharField(max_length=250)),
                ('año', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Año.año')),
                ('mes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mes.mes')),
                ('tipo_valor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TipoValor.tipovalor')),
            ],
        ),
        migrations.CreateModel(
            name='AsalariadosRama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sin_estacionalidad', models.CharField(max_length=250)),
                ('con_estacionalidad', models.CharField(max_length=250)),
                ('año', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Año.año')),
                ('mes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mes.mes')),
                ('rama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sectorPrivado.ramaactividad')),
                ('tipo_valor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TipoValor.tipovalor')),
            ],
        ),
    ]
